import { existsSync } from 'fs';
import { defineConfig } from 'vitest/config';
import { svelte } from '@sveltejs/vite-plugin-svelte';
import { playwright } from '@vitest/browser-playwright';

// icons.css is generated by scripts/subset-icons.mjs and gitignored.
// Stub it to an empty string in tests so they pass without generating the font.
const iconsPath = new URL('src/client/css/icons.css', import.meta.url).pathname;

/**
 * Vite plugin that stubs the generated icons.css import when the file doesn't exist.
 * This allows tests to run in CI or fresh clones without first running the subset script.
 * @return {import('vite').Plugin} The Vite plugin
 */
function stubIconsCSS(): import('vite').Plugin {
  return {
    name: 'stub-icons-css',
    resolveId(id: string) {
      if (id.endsWith('css/icons.css') && !existsSync(iconsPath)) {
        return '\0stub-icons-css';
      }
    },
    load(id: string) {
      if (id === '\0stub-icons-css') return '';
    },
  };
}

export default defineConfig({
  test: {
    // Inline project definitions replace the separate vitest.workspace.ts file.
    // This keeps the config co-located with package.json so Vite's config
    // search stops here rather than walking up to the parent repo root.
    projects: [
      //////////////////////////////
      // Unit tests — Node.js environment (pure JS/TS, no DOM)
      //////////////////////////////
      {
        plugins: [svelte(), stubIconsCSS()],
        test: {
          name: 'unit',
          include: [
            'tests/**/*.test.ts',
            '!tests/e2e/**',
            '!tests/**/*components*/**',
          ],
          setupFiles: ['tests/setup.ts'],
          coverage: {
            provider: 'v8',
            reportsDirectory: '.coverage',
          },
        },
      },

      //////////////////////////////
      // Component tests — jsdom environment (Svelte components via @testing-library/svelte)
      //////////////////////////////
      {
        plugins: [svelte(), stubIconsCSS()],
        // browser condition is required so Vite resolves Svelte's client-side
        // entry point instead of the SSR server entry, which does not have `mount`
        resolve: {
          conditions: ['browser'],
          // @codemirror/* and @lezer/* require a real browser DOM that jsdom cannot
          // provide. Redirect them to a stub so EditorPane (and its transitive
          // imports) can be loaded in the jsdom test environment.
          alias: [
            {
              find: /^@codemirror\/.+/,
              replacement: new URL('tests/stubs/codemirror.ts', import.meta.url)
                .pathname,
            },
            {
              find: /^@lezer\/.+/,
              replacement: new URL('tests/stubs/codemirror.ts', import.meta.url)
                .pathname,
            },
          ],
        },
        test: {
          name: 'components',
          environment: 'jsdom',
          include: ['tests/**/components/**/*.test.ts'],
          setupFiles: ['tests/setup.ts'],
        },
      },

      //////////////////////////////
      // Browser tests — Playwright via system Chrome
      //////////////////////////////
      {
        plugins: [
          svelte(),
          stubIconsCSS(),
          // Stub plugin that resolves virtual:collections for the browser test
          // environment. The real virtual:collections plugin is injected by the
          // Astro integration, which is not running during Vitest browser tests.
          // It is mocked in tests, but Vite's dependency scanner runs before
          // mocks are applied and would fail without a resolver.
          {
            name: 'stub-virtual-modules',
            /**
             * Resolves virtual:collections to an internal stub so Vite's dependency scanner doesn't fail before mocks apply.
             * @param {string} id - The module specifier to resolve
             * @return {string | undefined} The resolved internal ID, or undefined to skip
             */
            resolveId(id: string) {
              if (id === 'virtual:collections') return '\0virtual:collections';
            },
            /**
             * Provides stub module source for virtual:collections.
             * @param {string} id - The internal module ID to load
             * @return {string | undefined} The module source code, or undefined to skip
             */
            load(id: string) {
              if (id === '\0virtual:collections') return 'export default {};';
            },
          },
        ],
        // Exclude @testing-library/svelte-core from pre-bundling so its
        // .svelte.js files go through the Svelte plugin's transform pipeline
        // (Vite pre-bundling skips plugin transforms, which leaves $state
        // runes uncompiled and causes ReferenceError at runtime).
        optimizeDeps: {
          exclude: ['@testing-library/svelte-core'],
        },
        // browser condition ensures Vite resolves Svelte's client-side entry
        // instead of the SSR server entry. @codemirror/* and @lezer/* are
        // stubbed because browser tests mock the editor — the same stub used
        // by component tests is reused here.
        resolve: {
          conditions: ['browser'],
          alias: [
            {
              find: /^@codemirror\/.+/,
              replacement: new URL('tests/stubs/codemirror.ts', import.meta.url)
                .pathname,
            },
            {
              find: /^@lezer\/.+/,
              replacement: new URL('tests/stubs/codemirror.ts', import.meta.url)
                .pathname,
            },
          ],
        },
        test: {
          name: 'browser',
          include: ['tests/e2e/**/*.test.ts'],
          browser: {
            enabled: true,
            headless: true,
            // Uses system Chrome via the 'chrome' channel to avoid downloading
            // a separate Chromium binary. CI adds --no-sandbox because most CI
            // containers lack the kernel namespace support sandboxing requires.
            provider: playwright({
              launchOptions: {
                channel: 'chrome',
                ...(process.env.CI
                  ? { args: ['--no-sandbox', '--disable-setuid-sandbox'] }
                  : {}),
              },
            }),
            instances: [{ browser: 'chromium' }],
          },
        },
      },
    ],
  },
});
